### ISSUE TITLE
DocumentDB emulator self signed error

### ISSUE THREAD

**Issue by DominicBoettger** [Azure/azure-documentdb-node#153]
When trying to use the library with the documentDB emulator the connection fails with:

```js
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```

I did not find a option to allow self signed certificates for the connection.

**Comment by jagratimodi** [comment]
Hi @DominicBoettger,
Look at : "Issues connecting with DocumentDB Emulator using Node SDK #157". This might help you to solve 'DocumentDB emulator self signed certificate' error.

**Comment by rnagpal** [comment]
@DominicBoettger We fixed this issue with the 1.10.1 release of the SDK, so please upgrade and let us know if that fixes the issue.

**Comment by moderakh** [comment]
@DominicBoettger @rnagpal 
I am closing this issue as it is fixed in the latest release of sdk and emulator. If you face this issue again please re-open.

**Comment by jacktho** [comment]
The connection still fails when connecting to the documentDB emulator for me. In 1.10.2 and 1.10.1.

`{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }`

**Comment by tstpierre** [comment]
Same issue, snippet from unit test:
```
  documentDbFactory
    getOrCreateDatabase
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
      1) should create database when not found
```

**Comment by uredkar** [comment]
I am getting the same error.
Error: self signed certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)

The following is my package.json, I just upgraded to new version of nodejs.
{
  "name": "Todo",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "description": "Building a Todo List application with DocumentDB",
  "author": {
    "name": "",
    "email": ""
  },
  "dependencies": {
    "async": "^2.1.2",
    "body-parser": "~1.15.2",
    "cookie-parser": "~1.4.3",
    "debug": "~2.2.0",
    "documentdb": "^1.12.0",
    "express": "~4.14.0",
    "jade": "~1.11.0",
    "morgan": "~1.7.0",
    "serve-favicon": "~2.3.0"
  }
}

**Comment by dimoibiehg** [comment]
The following setting for client works for me in typescript:

    export var docDbClient = new DocumentClient(dbConfig.endPoint, {
    masterKey: dbConfig.peimaryKey
    },
    {
        DisableSSLVerification :true,
        EnableEndpointDiscovery : false,
        MediaReadMode : "Buffered",
        RequestTimeout : 10000,
        MediaRequestTimeout : 10000,
        PreferredLocations : [],
        RetryOptions: {}
    });

**Comment by moderakh** [comment]
interacting to documentdb uses SSL. since emulator certificate is self signed you need disable SSL verification when interacting with emulator.

@uredkar  so as @dimoibiehg pointed out if you pass 'DisableSSLVerification : true' it should work for you.

**Comment by Hosar** [comment]
I solved this issue using **https** on the endpoint
https://localhost:8081/
And setting the following when running the script.
**set NODE_TLS_REJECT_UNAUTHORIZED=0**

**Comment by moderakh** [comment]
@Hosar yes set NODE_TLS_REJECT_UNAUTHORIZED=0 works too however the problem with that is it will disable tls authorization across your node runtime not for only the https://localhost:8081/ which was intended.
