### ISSUE TITLE
Unauthorized, The input authorization token can't serve the request

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-documentdb-node#82]
Localhost everything works fine, but when a i made a deploy i'm getting this error.

ActivityId: 39d58ef7-0df9-436d-a803-06991ee62424 
 { code: 401,
  body: '{"code":"Unauthorized","message":"The input authorization token can\'t serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: \'post\ndbs\n\nthu, 29 oct 2015 18:52:39 gmt\n\n\'\r\nActivityId: 39d58ef7-0df9-436d-a803-06991ee62424"}' }

any guess?

Thanks!

**Comment by akhadem** [comment]
same

**Comment by ryancrawcour** [comment]
Cannot repro this issue. Can someone please post a repro project. 

What are you deploying to? Azure Web applications, VMS, something else?

**Comment by mauricionr** [comment]
In my case is an Azure nodjes web app with Azure DocumentDB

**Comment by ryancrawcour** [comment]
Is your node.js web app and the DocumentDB in the same Azure region?

**Comment by ryancrawcour** [comment]
Is this still an issue?

**Comment by matthiasotto** [comment]
Just encountered this:

`{"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get\n\n\ntue, 09 feb 2016 18:46:42 gmt\n\n'\r\nActivityId: 143aa10b-ec48-4788-9306-6be7eaf15b78"}`

**Comment by maodd** [comment]
I got same issue when running the databasemanagement.js sample: https://github.com/Azure/azure-documentdb-node/blob/master/samples/DatabaseManagement/app.js

**Comment by maodd** [comment]
never mind, updated client lib from 0.9.4 to 1.5.5. problem went away.

**Comment by ryancrawcour** [comment]
due to the fact i can't replicate this, and that @maodd has reported it went away, i'm wondering if this is a transient issue. will leave it open and track for a bit more.

**Comment by ryancrawcour** [comment]
@matthiasotto @mauricionr @akhadem could you please confirm which version of the node SDK you are using? If you are using an old version of the SDK could you please upgrade to the latest version and try again.

**Comment by syantien** [comment]
Hi.  I also get this error: Microsoft.Azure.Documents.DocumentClientException: The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'post
docs
xwfmaksjxqa=
sat, 05 mar 2016 05:53:08 gmt.

I seem to get this randomly.  My SDK version is 1.5.3.

**Comment by ryancrawcour** [comment]
@syantien that error looks like .NET? are you using .NET SDK or the Node SDK?

**Comment by thivy** [comment]
I get this same error when I create a DocDb project from Visual Studio quick start. 

I noticed the Nuget packages are different 
https://onedrive.live.com/redir?resid=4417247F8CE54DFE!44829&authkey=!ADXvKRgNo3eai5Y&v=3&ithint=photo%2cPNG

**Comment by thivy** [comment]
@ryancrawcour I had the same error. It turns out when I copied the PRIMARY KEY from the portal it only copied what you see on screen. 

When you guys copy the PRIMARY KEY make sure to copy using Click to Copy button, instead of using the mouse select.

**Comment by julielerman** [comment]
I'm getting this same error after updating to current SDK and using Upsert instead of replace. All of my queries are fine. I have been using the key for a long time with replace working as expected.  I'll keep googlebinging.

**Comment by ryancrawcour** [comment]
If you're using ID based routing, i.e. your links contain your own IDs not the internal system rid e.g. dbs/mydatabaseid/colls/mycollectionid then check that you don't have a trailing /

**Comment by julielerman** [comment]
getting closer. I started out with this (following an example in the blog post that announced no more dependency self links)
   var docLink = "dbs/Ninjas/colls/Ninjas/docs/"+ item.Id;   
   
now I'm down to 

 var docLink = "dbs/Ninjas/colls/Ninjas"  and letting upsert find the id in the item passed into the 2nd parameter.

No error.  

Data not updated either ;), but I'm sure that's something silly. Will update you . And thanks! Given that you're not on the documentdb team anymore. :)

**Comment by julielerman** [comment]
found it. Somewhere along the line I had specified the Id property as [capital]Id so it wasn't matching [lowercase]id in the database and doing an insert instead

**Comment by ryancrawcour** [comment]
Yeah, this is still an open issue to resolve this trailing / thing in the node.js driver properly. It shouldn't care if there's a trailing / or not. 

Just thought I'd unblock you seeing as I knew what the cause was.

**Comment by rnagpal** [comment]
Thanks Ryan for jumping in here!

I'll look into fixing the trailing / in the Node SDK.

**Comment by julielerman** [comment]
thanks also for the node sdk and for the q wrapper!! See https://github.com/julielerman/AureliaDocDB for how I implemented it. Want me to update your sample documentation? ;)

**Comment by mauricionr** [comment]
@ryancrawcour sorry for my long delay, I'm currently not using documentDB.
I've changed to [azure mobile app service](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-node-backend-how-to-use-server-sdk/)

**Comment by 1N50MN14** [comment]
Is there anyone maintaining the node.js SDK at all? I'm surprised such a critical issue is still standing we're pretty much unable to use the SDK because of it..

**Comment by rnagpal** [comment]
@1N50MN14 Looks like the thread diverged. Are you running into the auth issue(401 error)?
Can you send me the error message with AcivityId so that we can look into it? Sample code where you hit this issue will help us repro. You get an authorization error even when the Id contains an invalid char, so please verify that the id of the resource doesn't contain any of the chars listed in https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.documents.resource.id.aspx#P:Microsoft.Azure.Documents.Resource.Id

**Comment by 1N50MN14** [comment]
@rnagpal Yes you were right there, in addition to that I also had a malformed collection link somehow I assumed `'dbs/'+databaseId+'/colls/'+collectionId+'/docs'` to be used with creating documents, omitting `/docs`solved it

**Comment by moderakh** [comment]
I am closing it (as it seems the problem is solved). If you think this is a bug in most recent version of nodejs sdk please feel free to reopen.

**Comment by paullintilhac** [comment]
I had the same error, and resolved it by using my primary read-only key in azure instead of my primary read/write key

**Comment by crowster** [comment]
My problem was very simple,  I was using a bad url

**Comment by JasonGreenAmerica** [comment]
@julielerman how did you get docs out of your path. I'm seeing the trailing "docs" in the swift sdk.
"dbs/Ninjas/colls/Ninjas/docs/"

**Comment by davidljuba15031979** [comment]
My problem was **wrong connection string**. 

In _Azure Portal_, I checked and compared `AzureCosmosDBConnectionString` from 

 _Function app_ -> _Configuration_ 

and 

 _Azure Cosmos DB Account_ -> _Keys_ -> _Primary connection string_

**Comment by faustofjunqueira** [comment]
Hy people,
At this moment, I have the same problem. In my case, my clock is wrong! I fix the time and redo the request. I hope help someone.

**Comment by gerardsimons** [comment]
Forgot to change the URL when I did change the key, thanks for the comments here for pointing me in the right direction!

**Comment by Aodhanob** [comment]
> o Cop

THIS IS THE CAUSE!!!

THANK YOU!!!

**Comment by ankitgupta2oct** [comment]
> @ryancrawcour I had the same error. It turns out when I copied the PRIMARY KEY from the portal it only copied what you see on screen.
> 
> When you guys copy the PRIMARY KEY make sure to copy using Click to Copy button, instead of using the mouse select.

Thanks, This solved the issue for me.
